# Generated by Django 5.2 on 2026-09-16 07:07

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]